##PORT
server:
  port: ${APP_PORT:8082}

spring:
  application:
    name: expense-service

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: dd-MM-yyyy HH:mm:ss


  ## mysql connection
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:expense-manager-db}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver


  ## jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

service:
  category:
    name: category-service
    url: ${CATEGORY_SERVICE_URL:http://CATEGORY-SERVICE}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs