server:
  port: 9090

spring:
  application:
    name: Gateway-Service
  cloud:
    circuitbreaker:
      enabled: true
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 2000
            response-timeout: 8s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Category-API
        url: /api-docs/category
      - name: Expense-Service
        url: /api-docs/expense

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
  #Resilience4J time-limiter Properties
  timelimiter:
    configs:
      default:
        timeout-duration: 8s

