server:
  port: 9090

spring:
  application:
    name: Gateway-Service
  cloud:
    circuitbreaker:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Category-API
        url: /api-docs/category
      - name: Expense-Service
        url: /api-docs/expense

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        autoTransitionFromOpenToHalfOpenEnabled: true

    retry:
      configs:
        default:
          maxAttempts: 3
          waitDuration: 5s

    timeLimiter:
      configs:
        default:
          timeoutDuration: 3s
